### ISSUE TITLE
Need explanation on redelivery

### ISSUE THREAD

**Issue by arunkjn** [softwaremill/kmq#3]
Hi,

Great project. I was looking for 'per message acknowledgement' for a project and this seems to be a brilliant approach. I wanted to know more about how the redelivery tracker works.

The following section from the docs was not very clear -

> When a marker has been received from a partition recently, the maximum such timestamp is used as the value of "now" - as it indicates exactly how far we are in processing the partition. What "recently" means depends on the useNowForRedeliverDespiteNoMarkerSeenForMs config setting. Otherwise, the current system time is used, as we assume that all markers from the partition have been processed.

When a start marker for an offset has been added, how will the redelivery tracker know if the end marker has arrived or not?
I am assuming that the redelivery tracker will scan the marker topic periodically from start to end.
It will check the start markers which are due past their timeout. If there is no end marker for the same it will be sent back to the main topic to be processed.
In the marker topic how do we get rid of 'start markers' which have been acknowledged? Do we commit them with kafka broker?

**Comment by adamw** [comment]
The redelivery tracker consumes the markers topic as any other topic - it doesn't do any special "scanning". It simply reads the data from the topic and creates an in-memory representation of which offsets are consumed, and which are not.

The tracker periodically checks if the in-memory representation contains any markers for which no end marker has been received for the configured period of time (the message timeout). If so, it redelivers the messages.

As for cleaning the markers topic, you should probably use a normal retention policy as for any other Kafka topic; you can use short retention time, as any markers which are older than the configured timeout will cause message redelivery anyway.

**Comment by arunkjn** [comment]
Got it!

In case a redelivery tracker fails, upon restart It needs to recreate this in memory state for which it has to read the topic from the beginning and not from the last commited offset. Am I correct in assuming that?

Also when using multiple copies of redelivery tracker, they will be responsible to track a set of partitions assigned to them. In a dynamic environment where I want to scale the number of redelivery trackers according to the marker topic size, how do we handle reassignment of partitions when introducing new trackers?

**Comment by adamw** [comment]
Partition reassignment for redelivery trackers is done automatically by Kafka - as for any other topics; they simple form a consumer group.

After failure, the markers are read from the last commited offset. In case of the redelivery tracker, only offsets are commited before which all messages are either properly delivered (there was an "end" marker) or redelivered. So in fact, you should be able to remove all data from the topic that is before the redelivery marker

**Comment by arunkjn** [comment]
Yeah that explains the commiting and restart behaviour very clearly.

Just regarding the first point I had the following doubt-

Consider a scenario where there are six partitions a, b, c, d, e, f
There are two instances of redelivery trackers each have been assigned topics a,b,c and d,e,f respectively.
A third instance of redelivery tracker now joins the consumer group and the partitions have been reassigned as follows-
tracker 1 - a, b
tracker 2 - d, e
tracker 3 - c, f

Tracker 1 and 2 are still tracking the state of partitions c and f respectively in memory. They will however never receive the end markers for those messages and hence redeliver them although c and f are now being tracked by tracker 3.

Are we taking care of handling this scenario?

**Comment by adamw** [comment]
Yes, this is done in maybe a simplistic way, but it ensures everything is working fine: when there's a new RT joining or leaving, which causes a re-balance of the consumer groups, all of the old state is thrown away, and the in-memory data is created anew (starting from the last committed offset). So in this scenario tracker 1 would track only partitions a, b.

**Comment by arunkjn** [comment]
perfect! Thanks closing this ticket
