### ISSUE TITLE
SSL encryption & authentication

### ISSUE THREAD

**Issue by MohamedEL59** [softwaremill/kmq#6]
Hello,

For the kmq project, is it possible to activate **ssl encryption and ssl authentication** ?

Best regards,
Mohamed

**Comment by adamw** [comment]
Sure, you can activate anything that the base Kafka offers. kmq is just an application written on top of Kafka.

**Comment by MohamedEL59** [comment]
Hello,

I have created [pull request](https://github.com/softwaremill/kmq/pull/8) API more flexible to add extra configuration settings.

Best regards,
Mohamed
