### ISSUE TITLE
Make KafkaClients class more flexible

### ISSUE THREAD

**Issue by Blasku** [softwaremill/kmq#7]
Hi!

I've started using your implementation and I really like it. The only question I have is why can't I add extra configuration settings when calling the `createConsumer` function, as opposed to `createProducer` which allows for such a thing (`Map<String, Object> extraConfig` argument).

TIA!

**Comment by MohamedEL59** [comment]
Hello,

I have created [pull request ](https://github.com/softwaremill/kmq/pull/8) API more flexible to add extra configuration settings.

Best regards,
Mohamed

**Comment by adamw** [comment]
Fixed in 0.2.2
