### ISSUE TITLE
Explanation regarding re-delivery tracker

### ISSUE THREAD

**Issue by shubhamDhoble** [softwaremill/kmq#9]
Hey, 
I was using this project and some doubts regarding the implementation of the re-delivery tracker and its limitations. My doubts are:

1. As per the logic, if I spawn multiple redelivery trackers on one topic for one client, I should spawn redelivery tracker with the same group-id. Then one record of marker would go to eighter of the tracker, which is then stored in the in-memory storage. My point does these multiple redelivery trackers shared same in memory storage? If not then there would be a problem in case one tracker gets the start marker while other get the end marker.

2. If it is an in-memory storage, can it be accessed over multiple JVMs?  So if multiple copies of kmq are running in different JVMs with the same group-id. All should be accessing same memory storage.

**Comment by adamw** [comment]
1. the start/end markers will always end up in the same redelivery tracker as they are partitioned basing on the partition of the message, see: https://github.com/softwaremill/kmq/blob/master/core/src/main/java/com/softwaremill/kmq/ParititionFromMarkerKey.java

2. no, there's no need to share the memory storage. Why would there be?
